# -*- encoding : utf-8 -*-

u1 = User.create(username: 'admin', password: 'admin', password_confirmation: 'admin', gender: 'F', active: true,
                 name: 'Maria Eugenia', last_name1: 'Sánchez', user_type: 'admin')
u2 = User.create(username: 'cord1', password: 'cord1', password_confirmation: 'cord1', gender: 'F', active: true,
                 name: 'Coordinador de Test', user_type: 'coordinator')

oc1 = Occupation.create(name: 'Auxiliar', admin_leave_days: 3, vacation_days: 5)
oc2 = Occupation.create(name: 'Supervisor', admin_leave_days: 5, vacation_days: 10)

e1 = Employee.create(name: 'Francisco Javier', last_name1: 'Sandoval',
                     last_name2: 'Aburto', gender: 'M', occupation: oc1)
e2 = Employee.create(name: 'Pablo', last_name1: 'Cruz', gender: 'M', occupation: oc1)
e3 = Employee.create(name: 'Giovanni', last_name1: 'De Lucca', gender: 'M', occupation: oc1)
e4 = Employee.create(name: 'Larry', last_name1: 'Capizza', gender: 'M', occupation: oc2)

sh1 = Shift.create(name: 'Turno mañana lun-vie',
                   monday: true, tuesday: true, wednesday: true, thursday: true, friday: true,
                   start_time: Time.new(2013, nil, nil, 6, 0),
                   end_time: Time.new(2013, nil, nil, 12, 0))
sh2 = Shift.create(name: 'Turno tarde lun-dom',
                   monday: true, tuesday: true, wednesday: true, thursday: true, friday: true, saturday: true, sunday: true,
                   start_time: Time.new(2013, nil, nil, 12, 0),
                   end_time: Time.new(2013, nil, nil, 18, 0))

e1.shifts << sh1
e2.shifts << sh1
e3.shifts << sh2



#--------------------------------RoomsLoader---------------------------------
s1 = Sector.create(name: 'Banco De Sangre', zone:'Crítico')
s2 = Sector.create(name: 'Centro Médico', zone:'INDEFINIDO')
s3 = Sector.create(name: 'Días Camas', zone:'INDEFINIDO')
s4 = Sector.create(name: 'Hospitalización', zone:'No Crítico')
s5 = Sector.create(name: 'Hospitalización Maternidad', zone:'Crítico')
s6 = Sector.create(name: 'Imagenología', zone:'No Crítico')
s7 = Sector.create(name: 'Lab. Anatomía Patológica', zone:'')
s8 = Sector.create(name: 'Laboratorio', zone:'INDEFINIDO')
s9 = Sector.create(name: 'Maternidad', zone:'Crítico')
s10 = Sector.create(name: 'OTROS', zone:'INDEFINIDO')
s11 = Sector.create(name: 'Pabellón', zone:'Crítico')
s12 = Sector.create(name: 'Pediatría', zone:'INDEFINIDO')
s13 = Sector.create(name: 'Salud Mental', zone:'INDEFINIDO')
s14 = Sector.create(name: 'Toma De Muestras', zone:'No Crítico')
s15 = Sector.create(name: 'Upc Adulto', zone:'INDEFINIDO')
s16 = Sector.create(name: 'Upc Adulto Aislado', zone:'INDEFINIDO')
s17 = Sector.create(name: 'UPC Pediátrica', zone:'INDEFINIDO')
s18 = Sector.create(name: 'Urgencia', zone:'No Crítico')
s19 = Sector.create(name: 'Vacunatorio', zone:'No Crítico')

Room.create(building: 'B', name: 'B-2057 Banco de Sangre', sector_id: s1.id, status: 'free')
Room.create(building: 'A', name: 'A 2001 Consulta Pediátrica Nº4', sector_id: s2.id, status: 'free')
Room.create(building: 'A', name: 'A 2002 Consulta Pediátrica Nº3', sector_id: s2.id, status: 'free')
Room.create(building: 'A', name: 'A 2003 Consulta Pediátrica Nº2', sector_id: s2.id, status: 'free')
Room.create(building: 'A', name: 'A 2004 Consulta Pediátrica Nº1', sector_id: s2.id, status: 'free')
Room.create(building: 'A', name: 'A 2010 Consulta Pediátrica Nº5', sector_id: s2.id, status: 'free')
Room.create(building: 'A', name: 'A 2011 Consulta General Nº6', sector_id: s2.id, status: 'free')
Room.create(building: 'A', name: 'A 2012 Consulta General Nº7', sector_id: s2.id, status: 'free')
Room.create(building: 'A', name: 'A 2014 Sala Curac. Pediátrica N°1', sector_id: s2.id, status: 'free')
Room.create(building: 'A', name: 'A 2046 Consulta General Nº14', sector_id: s2.id, status: 'free')
Room.create(building: 'A', name: 'A 2047 Consulta General Nº15', sector_id: s2.id, status: 'free')
Room.create(building: 'A', name: 'A 2048 Consulta General Nº16', sector_id: s2.id, status: 'free')
Room.create(building: 'A', name: 'A 2049 Consulta General Nº17', sector_id: s2.id, status: 'free')
Room.create(building: 'A', name: 'A 2056 Espirometría N°4', sector_id: s2.id, status: 'free')
Room.create(building: 'A', name: 'A 2062 Consulta Salud Mental Nº18', sector_id: s2.id, status: 'free')
Room.create(building: 'A', name: 'A 2064 Consulta Psicológica N° 22', sector_id: s2.id, status: 'free')
Room.create(building: 'A', name: 'A 2065 Consulta Psiquiátrica N° 21', sector_id: s2.id, status: 'free')
Room.create(building: 'A', name: 'A 2073 Consulta Salud Mental Nº2', sector_id: s2.id, status: 'free')
Room.create(building: 'A', name: 'A 2074 Consulta Salud Mental Nº19', sector_id: s2.id, status: 'free')
Room.create(building: 'A', name: 'A 3001 Consulta General Nº1', sector_id: s2.id, status: 'free')
Room.create(building: 'A', name: 'A 3002 Consulta Ginecológica Nº2', sector_id: s2.id, status: 'free')
Room.create(building: 'A', name: 'A 3007 Consulta Ginecológica Nº1', sector_id: s2.id, status: 'free')
Room.create(building: 'A', name: 'A 3016 Consulta Ginecológica Nº3', sector_id: s2.id, status: 'free')
Room.create(building: 'A', name: 'A 3021 Consulta Ginecológica Nº4', sector_id: s2.id, status: 'free')
Room.create(building: 'A', name: 'A 3022 Box Audiológico', sector_id: s2.id, status: 'free')
Room.create(building: 'A', name: 'A 3023 Consulta General Nº2', sector_id: s2.id, status: 'free')
Room.create(building: 'A', name: 'A 3024 Consulta General Nº3', sector_id: s2.id, status: 'free')
Room.create(building: 'A', name: 'A 3025 Consulta General Nº4', sector_id: s2.id, status: 'free')
Room.create(building: 'A', name: 'A 3026 Consulta General Nº5', sector_id: s2.id, status: 'free')
Room.create(building: 'A', name: 'A 3027 Consulta General Nº6', sector_id: s2.id, status: 'free')
Room.create(building: 'A', name: 'A 3035 Eco Cg', sector_id: s2.id, status: 'free')
Room.create(building: 'A', name: 'A 3036 Test Esfuerzo', sector_id: s2.id, status: 'free')
Room.create(building: 'A', name: 'A 3047 Sala De Holter Y Ecg', sector_id: s2.id, status: 'free')
Room.create(building: 'A', name: 'A  Sala Octavo Par', sector_id: s2.id, status: 'free')
Room.create(building: 'A', name: 'A 3052 Consulta General Nº8', sector_id: s2.id, status: 'free')
Room.create(building: 'A', name: 'A 3053 Consulta General Nº9', sector_id: s2.id, status: 'free')
Room.create(building: 'A', name: 'A 3054 Consulta General Nº10', sector_id: s2.id, status: 'free')
Room.create(building: 'A', name: 'A 3055 Consulta General Nº11', sector_id: s2.id, status: 'free')
Room.create(building: 'A', name: 'A 3056 Consulta General Nº12', sector_id: s2.id, status: 'free')
Room.create(building: 'A', name: 'A 3057 Examen Oftalmológico', sector_id: s2.id, status: 'free')
Room.create(building: 'A', name: 'A 3060 Consulta Oftalmológica', sector_id: s2.id, status: 'free')
Room.create(building: 'A', name: 'A 3061 Procedimiento 2', sector_id: s2.id, status: 'free')
Room.create(building: 'A', name: 'A 3062 Consulta Oftalmológica', sector_id: s2.id, status: 'free')
Room.create(building: 'A', name: 'A 3071 Urología 1', sector_id: s2.id, status: 'free')
Room.create(building: 'A', name: 'A 3072 Urología 2', sector_id: s2.id, status: 'free')
Room.create(building: 'B', name: 'B 3066 Habitación N°11    ', sector_id: s3.id, status: 'free')
Room.create(building: 'B', name: 'B 3067 Habitación N°10    ', sector_id: s3.id, status: 'free')
Room.create(building: 'B', name: 'B 3070 Habitación N°9    ', sector_id: s3.id, status: 'free')
Room.create(building: 'B', name: 'B 3085 Habitación N°1', sector_id: s3.id, status: 'free')
Room.create(building: 'B', name: 'B 3088 Habitación N°2', sector_id: s3.id, status: 'free')
Room.create(building: 'B', name: 'B 3089 Habitación N°3', sector_id: s3.id, status: 'free')
Room.create(building: 'B', name: 'B 3092 Habitación N°4', sector_id: s3.id, status: 'free')
Room.create(building: 'B', name: 'B 3093 Habitación N°5    ', sector_id: s3.id, status: 'free')
Room.create(building: 'B', name: 'B 3097 Habitación N°6    ', sector_id: s3.id, status: 'free')
Room.create(building: 'B', name: 'B 3098 Habitación N°7    ', sector_id: s3.id, status: 'free')
Room.create(building: 'B', name: 'B 3101 Habitación N°8    ', sector_id: s3.id, status: 'free')
Room.create(building: 'C', name: 'C 1016 Habitación N°21', sector_id: s4.id, status: 'free')
Room.create(building: 'C', name: 'C 1017 Habitación N°20', sector_id: s4.id, status: 'free')
Room.create(building: 'C', name: 'C 1013 Habitación N°22', sector_id: s4.id, status: 'free')
Room.create(building: 'C', name: 'C 1026 Habitación N°2', sector_id: s4.id, status: 'free')
Room.create(building: 'C', name: 'C 1027 Habitación N°3', sector_id: s4.id, status: 'free')
Room.create(building: 'C', name: 'C 1030 Habitación N°4', sector_id: s4.id, status: 'free')
Room.create(building: 'C', name: 'C 1031 Habitación N°5', sector_id: s4.id, status: 'free')
Room.create(building: 'C', name: 'C 1035 Habitación N°19', sector_id: s4.id, status: 'free')
Room.create(building: 'C', name: 'C 1036 Habitación N°18', sector_id: s4.id, status: 'free')
Room.create(building: 'C', name: 'C 1045 Habitación N°6', sector_id: s4.id, status: 'free')
Room.create(building: 'C', name: 'C 1046 Habitación N°7', sector_id: s4.id, status: 'free')
Room.create(building: 'C', name: 'C 1053 Habitación N°17', sector_id: s4.id, status: 'free')
Room.create(building: 'C', name: 'C 1054 Habitación N°16', sector_id: s4.id, status: 'free')
Room.create(building: 'C', name: 'C 1060 Habitación N°8', sector_id: s4.id, status: 'free')
Room.create(building: 'C', name: 'C 1061 Habitación N°9', sector_id: s4.id, status: 'free')
Room.create(building: 'C', name: 'C 1067 Habitación N°15', sector_id: s4.id, status: 'free')
Room.create(building: 'C', name: 'C 1071 Habitación N°10', sector_id: s4.id, status: 'free')
Room.create(building: 'C', name: 'C 1075 Habitación N°11', sector_id: s4.id, status: 'free')
Room.create(building: 'C', name: 'C 1076 Habitación N°12', sector_id: s4.id, status: 'free')
Room.create(building: 'C', name: 'C 1079 Habitación N°13', sector_id: s4.id, status: 'free')
Room.create(building: 'C', name: 'C 1080 Habitación N°14', sector_id: s4.id, status: 'free')
Room.create(building: 'C', name: 'C 3000 Habitación N°1', sector_id: s4.id, status: 'free')
Room.create(building: 'C', name: 'C 3013 Habitación N°22', sector_id: s4.id, status: 'free')
Room.create(building: 'C', name: 'C 3016 Habitación N°21', sector_id: s4.id, status: 'free')
Room.create(building: 'C', name: 'C 3017 Habitación N°20', sector_id: s4.id, status: 'free')
Room.create(building: 'C', name: 'C 3026 Habitación N°2', sector_id: s4.id, status: 'free')
Room.create(building: 'C', name: 'C 3027 Habitación N°3', sector_id: s4.id, status: 'free')
Room.create(building: 'C', name: 'C 3030 Habitación N°4', sector_id: s4.id, status: 'free')
Room.create(building: 'C', name: 'C 3031 Habitación N°5    ', sector_id: s4.id, status: 'free')
Room.create(building: 'C', name: 'C 3035 Habitación N°19', sector_id: s4.id, status: 'free')
Room.create(building: 'C', name: 'C 3036 Habitación N°18', sector_id: s4.id, status: 'free')
Room.create(building: 'C', name: 'C 3045 Habitación N°6    ', sector_id: s4.id, status: 'free')
Room.create(building: 'C', name: 'C 3046 Habitación N°7    ', sector_id: s4.id, status: 'free')
Room.create(building: 'C', name: 'C 3053 Habitación N°17', sector_id: s4.id, status: 'free')
Room.create(building: 'C', name: 'C 3054 Habitación N°16', sector_id: s4.id, status: 'free')
Room.create(building: 'C', name: 'C 3060 Habitación N°8    ', sector_id: s4.id, status: 'free')
Room.create(building: 'C', name: 'C 3061 Habitación N°9', sector_id: s4.id, status: 'free')
Room.create(building: 'C', name: 'C 3067 Habitación N°15', sector_id: s4.id, status: 'free')
Room.create(building: 'C', name: 'C 3071 Habitación N°10    ', sector_id: s4.id, status: 'free')
Room.create(building: 'C', name: 'C 3075 Habitación N°11', sector_id: s4.id, status: 'free')
Room.create(building: 'C', name: 'C 3076 Habitación N°12', sector_id: s4.id, status: 'free')
Room.create(building: 'C', name: 'C 3079 Habitación N°13', sector_id: s4.id, status: 'free')
Room.create(building: 'C', name: 'C 3080 Habitación N°14', sector_id: s4.id, status: 'free')
Room.create(building: 'C', name: 'C 2000 Habitación N°1', sector_id: s5.id, status: 'free')
Room.create(building: 'C', name: 'C 2013 Habitación N°20', sector_id: s5.id, status: 'free')
Room.create(building: 'C', name: 'C 2016 Habitación N°19', sector_id: s5.id, status: 'free')
Room.create(building: 'C', name: 'C 2017 Habitación N°18', sector_id: s5.id, status: 'free')
Room.create(building: 'C', name: 'C 2026 Habitación N°2', sector_id: s5.id, status: 'free')
Room.create(building: 'C', name: 'C 2027 Habitación N°3', sector_id: s5.id, status: 'free')
Room.create(building: 'C', name: 'C 2030 Habitación N°4', sector_id: s5.id, status: 'free')
Room.create(building: 'C', name: 'C 2031 Habitación N°5', sector_id: s5.id, status: 'free')
Room.create(building: 'C', name: 'C 2035 Habitación N°17', sector_id: s5.id, status: 'free')
Room.create(building: 'C', name: 'C 2036 Habitación N°16', sector_id: s5.id, status: 'free')
Room.create(building: 'C', name: 'C 2045 Habitación N°6', sector_id: s5.id, status: 'free')
Room.create(building: 'C', name: 'C 2046 Habitación N°7', sector_id: s5.id, status: 'free')
Room.create(building: 'C', name: 'C 2054 Nursery', sector_id: s5.id, status: 'free')
Room.create(building: 'C', name: 'C 2054 Nursery', sector_id: s5.id, status: 'free')
Room.create(building: 'C', name: 'C 2060 Habitación N°8    ', sector_id: s5.id, status: 'free')
Room.create(building: 'C', name: 'C 2061 Habitación N°9', sector_id: s5.id, status: 'free')
Room.create(building: 'C', name: 'C 2067 Habitación N°15', sector_id: s5.id, status: 'free')
Room.create(building: 'C', name: 'C 2075 Habitación N°11', sector_id: s5.id, status: 'free')
Room.create(building: 'C', name: 'C 2076 Habitación N°12', sector_id: s5.id, status: 'free')
Room.create(building: 'C', name: 'C 2079 Habitación N°13', sector_id: s5.id, status: 'free')
Room.create(building: 'C', name: 'C 2080 Habitación N°14', sector_id: s5.id, status: 'free')
Room.create(building: 'B', name: 'B 1090 Scanner', sector_id: s6.id, status: 'free')
Room.create(building: 'B', name: 'B 1099 Mamografía', sector_id: s6.id, status: 'free')
Room.create(building: 'A', name: 'A-2015 Lab. Anatomía Patológica', sector_id: s7.id, status: 'free')
Room.create(building: 'A', name: 'A-2038 Laboratorio Clínico', sector_id: s8.id, status: 'free')
Room.create(building: 'B', name: 'B-1087 Preparto', sector_id: s9.id, status: 'free')
Room.create(building: 'A', name: 'A 2028 Consulta General Nº5', sector_id: s10.id, status: 'free')
Room.create(building: 'A', name: 'A 2029 Consulta General Nº6', sector_id: s10.id, status: 'free')
Room.create(building: 'A', name: 'A 2031 Consulta General Nº8', sector_id: s10.id, status: 'free')
Room.create(building: 'A', name: 'A 2032 Consulta General Nº9', sector_id: s10.id, status: 'free')
Room.create(building: 'A', name: 'A 2033 Consulta General Nº13', sector_id: s10.id, status: 'free')
Room.create(building: 'A', name: 'A 2035 Consulta General Nº12', sector_id: s10.id, status: 'free')
Room.create(building: 'A', name: 'A 2037 Electro Encefalograma N°2', sector_id: s10.id, status: 'free')
Room.create(building: 'B', name: 'B-1006 Endoscopía Nº1', sector_id: s11.id, status: 'free')
Room.create(building: 'B', name: 'B-1017 Endoscopía Nº2', sector_id: s11.id, status: 'free')
Room.create(building: 'B', name: 'B-1018 Endoscopía Nº3', sector_id: s11.id, status: 'free')
Room.create(building: 'B', name: 'B-1129 Angiografía', sector_id: s11.id, status: 'free')
Room.create(building: 'B', name: 'B-1146 Pabellón Nº1', sector_id: s11.id, status: 'free')
Room.create(building: 'B', name: 'B-1149 Pabellón Nº4', sector_id: s11.id, status: 'free')
Room.create(building: 'B', name: 'B-1165 Pabellón Nº2', sector_id: s11.id, status: 'free')
Room.create(building: 'B', name: 'B-1179 Pabellón Nº3', sector_id: s11.id, status: 'free')
Room.create(building: 'B', name: 'B-1177 Pabellón Nº5', sector_id: s11.id, status: 'free')
Room.create(building: 'B', name: 'B-1175 Pabellón Nº7', sector_id: s11.id, status: 'free')
Room.create(building: 'B', name: 'B-1178 Pabellón Nº6', sector_id: s11.id, status: 'free')
Room.create(building: 'C', name: 'C-1086 Habitación N°7', sector_id: s12.id, status: 'free')
Room.create(building: 'C', name: 'C-1087 Habitación N°8', sector_id: s12.id, status: 'free')
Room.create(building: 'C', name: 'C-2038 Habitación N°5', sector_id: s13.id, status: 'free')
Room.create(building: 'C', name: 'C-2041 Habitación N°6', sector_id: s13.id, status: 'free')
Room.create(building: 'C', name: 'C-2046 Box De Atención Personal', sector_id: s13.id, status: 'free')
Room.create(building: 'C', name: 'C-2049 Habitación N°4', sector_id: s13.id, status: 'free')
Room.create(building: 'C', name: 'C-2050 Habitación N°3', sector_id: s13.id, status: 'free')
Room.create(building: 'C', name: 'C-2057 Habitación N°7', sector_id: s13.id, status: 'free')
Room.create(building: 'C', name: 'C-2060 Habitación N°8', sector_id: s13.id, status: 'free')
Room.create(building: 'C', name: 'C-2066 Habitación N°2', sector_id: s13.id, status: 'free')
Room.create(building: 'C', name: 'C-2067 Habitación N°1', sector_id: s13.id, status: 'free')
Room.create(building: 'A', name: 'A 1027 Box Tm Nº1', sector_id: s14.id, status: 'free')
Room.create(building: 'A', name: 'A 1028a Box Tm Nº2', sector_id: s14.id, status: 'free')
Room.create(building: 'A', name: 'A 1028b Box Tm Nº3', sector_id: s14.id, status: 'free')
Room.create(building: 'A', name: 'A 1028c Box Tm Nº4', sector_id: s14.id, status: 'free')
Room.create(building: 'A', name: 'A 1028d Box Tm Nº5', sector_id: s14.id, status: 'free')
Room.create(building: 'A', name: 'A 1028e Box Tm Nº6', sector_id: s14.id, status: 'free')
Room.create(building: 'A', name: 'A 1028f Box Tm Nº7', sector_id: s14.id, status: 'free')
Room.create(building: 'A', name: 'A 1028g Box Tm Nº8', sector_id: s14.id, status: 'free')
Room.create(building: 'A', name: 'A 1028h Box Tm Nº9', sector_id: s14.id, status: 'free')
Room.create(building: 'A', name: 'A 1036 Box Tm Infantil Nº5', sector_id: s14.id, status: 'free')
Room.create(building: 'A', name: 'A 1039 Box Tm Infantil Nº1', sector_id: s14.id, status: 'free')
Room.create(building: 'B', name: 'B 2087 Habitación Nº2', sector_id: s15.id, status: 'free')
Room.create(building: 'B', name: 'B 2102 Habitación Nº4', sector_id: s15.id, status: 'free')
Room.create(building: 'B', name: 'B 2103 Habitación Nº5', sector_id: s15.id, status: 'free')
Room.create(building: 'B', name: 'B 2107 Habitación Nº6', sector_id: s15.id, status: 'free')
Room.create(building: 'B', name: 'B 2108 Habitación Nº7', sector_id: s15.id, status: 'free')
Room.create(building: 'B', name: 'B 2111 Habitación Nº8', sector_id: s15.id, status: 'free')
Room.create(building: 'B', name: 'B 2060 Habitación  Nº14 (Presión -)', sector_id: s16.id, status: 'free')
Room.create(building: 'B', name: 'B 2063 Habitación Nº13 (Presión -)', sector_id: s16.id, status: 'free')
Room.create(building: 'B', name: 'B 2064 Habitación Nº12 (Presión +)', sector_id: s16.id, status: 'free')
Room.create(building: 'B', name: 'B 2067 Habitación Nº11 (Presión +)', sector_id: s16.id, status: 'free')
Room.create(building: 'B', name: 'B 2112 Habitación Nº10', sector_id: s16.id, status: 'free')
Room.create(building: 'B', name: 'B 2115 Habitación Nº9', sector_id: s16.id, status: 'free')
Room.create(building: 'C', name: 'C-1059 Habitación N°1', sector_id: s17.id, status: 'free')
Room.create(building: 'C', name: 'C-1062 Habitación N°2', sector_id: s17.id, status: 'free')
Room.create(building: 'C', name: 'C-1063 Habitación N°3', sector_id: s17.id, status: 'free')
Room.create(building: 'C', name: 'C-1078 Habitación N°4', sector_id: s17.id, status: 'free')
Room.create(building: 'B', name: 'B 1138 Box 9', sector_id: s18.id, status: 'free')
Room.create(building: 'B', name: 'B 1139 Box 8', sector_id: s18.id, status: 'free')
Room.create(building: 'B', name: 'B 1140 Box 7', sector_id: s18.id, status: 'free')
Room.create(building: 'B', name: 'B 1141 Box 6', sector_id: s18.id, status: 'free')
Room.create(building: 'B', name: 'B 1143 Box 3', sector_id: s18.id, status: 'free')
Room.create(building: 'B', name: 'B 1145 Box 2', sector_id: s18.id, status: 'free')
Room.create(building: 'B', name: 'B 1155 Trauma Nº2', sector_id: s18.id, status: 'free')
Room.create(building: 'B', name: 'B 1158 Box 4', sector_id: s18.id, status: 'free')
Room.create(building: 'B', name: 'B 1159 Trauma Nº1', sector_id: s18.id, status: 'free')
Room.create(building: 'B', name: 'B 1164 Box 5', sector_id: s18.id, status: 'free')
Room.create(building: 'B', name: 'B 1173 Box 11', sector_id: s18.id, status: 'free')
Room.create(building: 'B', name: 'B 1174 Box 12', sector_id: s18.id, status: 'free')
Room.create(building: 'A', name: 'A 1039b Box Vacunatorio Nº1', sector_id: s19.id, status: 'free')
Room.create(building: 'A', name: 'A 1043 Box Vacunatorio Nº2', sector_id: s19.id, status: 'free')
